#pragma once
#include <pgmspace.h>

// Generated Juno-6 Patch Names (128 patches)
const char juno_patch_names[128][48] PROGMEM = {
    "A11 Brass Set 1                               ",
    "A12 Brass\nSwell                               ",
    "A13 Trumpet                                    ",
    "A14 Flutes                                     ",
    "A15 Moving\nStrings                            ",
    "A16 Brass &\nStrings                           ",
    "A17 Choir                                      ",
    "A18 Piano I                                    ",
    "A21 Organ I                                    ",
    "A22 Organ II                                   ",
    "A23 Combo\nOrgan                               ",
    "A24 Calliope                                   ",
    "A25 Donald\nPluck                              ",
    "A26 Celeste*\n(1 oct.up)                       ",
    "A27 Elect.\nPiano I                            ",
    "A28 Elect.\nPiano II                           ",
    "A31 Clock\nChimes* (1\noct. up)                ",
    "A32 Steel\nDrums                               ",
    "A33 Xylophone                                  ",
    "A34 Brass III                                  ",
    "A35 Fanfare                                    ",
    "A36 String\nIII                                ",
    "A37 Pizzicato                                  ",
    "A38 High\nStrings                              ",
    "A41 Bass\nclarinet                             ",
    "A42 English\nHorn                              ",
    "A43 Brass\nEnsemble                            ",
    "A44 Guitar                                     ",
    "A45 Koto                                       ",
    "A46 Dark\nPluck                                ",
    "A47 Funky I                                    ",
    "A48 Synth\nBass I (unison)                    ",
    "A51 Lead I                                     ",
    "A52 Lead II                                    ",
    "A53 Lead III                                   ",
    "A54 Funky II                                   ",
    "A55 Synth\nBass II                             ",
    "A56 Funky III                                  ",
    "A57 Thud Wah                                   ",
    "A58 Going Up                                   ",
    "A61 Piano II                                   ",
    "A62 Clav                                       ",
    "A63 Frontier\nOrgan                            ",
    "A64 Snare\nDrum (unison)                       ",
    "A65 Tom Toms\n(unison)                         ",
    "A66 Timpani\n(unison)                          ",
    "A67 Shaker                                     ",
    "A68 Synth Pad                                  ",
    "A71 Sweep I                                    ",
    "A72 Pluck\nSweep                               ",
    "A73 Repeater                                   ",
    "A74 Sweep II                                   ",
    "A75 Pluck\nBell                                ",
    "A76 Dark\nSynth Piano                          ",
    "A77 Sustainer                                  ",
    "A78 Wah\nRelease                               ",
    "A81 Gong\n(play low\nchords)                   ",
    "A82 Resonance\nFunk                            ",
    "A83 Drum Booms* \n(1 oct. down)                ",
    "A84 Dust\nStorm                                ",
    "A85 Rocket\nMen                                ",
    "A86 Hand\nClaps                                ",
    "A87 FX Sweep                                   ",
    "A88 Caverns                                    ",
    "B11 Strings                                    ",
    "B12 Violin                                     ",
    "B13 Chorus\nVibes                              ",
    "B14 Organ 1                                    ",
    "B15\nHarpsichord 1                             ",
    "B16 Recorder                                   ",
    "B17 Perc.\nPluck                               ",
    "B18 Noise\nSweep                               ",
    "B21 Space\nChimes                              ",
    "B22 Nylon\nGuitar                              ",
    "B23\nOrchestral\nPad                           ",
    "B24 Bright\nPluck                              ",
    "B25 Organ\nBell                                ",
    "B26 Accordion                                  ",
    "B27 FX Rise 1                                  ",
    "B28 FX Rise 2                                  ",
    "B31 Brass                                      ",
    "B32\nHelicopter                                ",
    "B33 Lute                                       ",
    "B34 Chorus\nFunk                               ",
    "B35 Tomita                                     ",
    "B36 FX Sweep\n1                                ",
    "B37 Sharp\nReed                                ",
    "B38 Bass\nPluck                                ",
    "B41 Resonant\nRise                             ",
    "B42\nHarpsichord 2                             ",
    "B43 Dark\nEnsemble                             ",
    "B44 Contact\nWah                               ",
    "B45 Noise\nSweep 2                             ",
    "B46 Glassy\nWah                                ",
    "B47 Phase\nEnsemble                            ",
    "B48 Chorused\nBell                             ",
    "B51 Clav                                       ",
    "B52 Organ 2                                    ",
    "B53 Bassoon                                    ",
    "B54 Auto\nRelease Noise\nSweep                 ",
    "B55 Brass\nEnsemble                            ",
    "B56 Ethereal                                   ",
    "B57 Chorus\nBell 2                             ",
    "B58 Blizzard                                   ",
    "B61 E. Piano\nwith Tremolo                     ",
    "B62 Clarinet                                   ",
    "B63 Thunder                                    ",
    "B64 Reedy\nOrgan                               ",
    "B65 Flute /\nHorn                              ",
    "B66 Toy\nRhodes                                ",
    "B67 Surf's Up                                  ",
    "B68 OW Bass                                    ",
    "B71 Piccolo                                    ",
    "B72 Melodic\nTaps                              ",
    "B73 Meow\nBrass                                ",
    "B74 Violin\n(high)                             ",
    "B75 High\nBells                                ",
    "B76 Rolling\nWah                               ",
    "B77 Ping Bell                                  ",
    "B78 Brassy\nOrgan                              ",
    "B81 Low Dark\nStrings                          ",
    "B82 Piccolo\nTrumpet                           ",
    "B83 Cello                                      ",
    "B84 High\nStrings                              ",
    "B85 Rocket\nMen                                ",
    "B86 Forbidden\nPlanet                          ",
    "B87 Froggy                                     ",
    "B88 Owgan                                      ",
};
